spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI}

# SERVICE TOKEN
service:
  token: 11111111-1111-1111-1111-111111111111
  
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.config: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.hometohome.user_service: DEBUG