version: '3.8'

services:
  pet-service:
    build: .
    ports:
      - "8082:8082"
    environment:
      - PET_DATASOURCE_URL=${PET_DATASOURCE_URL}
      - PET_DATASOURCE_USERNAME=${PET_DATASOURCE_USERNAME}
      - PET_DATASOURCE_PASSWORD=${PET_DATASOURCE_PASSWORD}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
    depends_on:
        - postgres
    networks:
      - h2h-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - h2h-network

networks:
  h2h-network:
    external: true

volumes:
  postgres_data: