server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cloud:
    config:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false