spring:
  application:
    name: chat-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI}

# Configuración JWT desde variable de entorno
jwt:
  secret: ${JWT_SECRET}

# SERVICE TOKEN
service:
  token: 11111111-1111-1111-1111-111111111111