server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          clone-on-start: true
          default-label: main
          search-paths: '{application}'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    registry-fetch-interval-seconds: 5