spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          clone-on-start: true
          default-label: main
          search-paths: .

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8888